# Generated by Django 4.1 on 2022-08-05 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainporto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='Lorem ipsum'),
        ),
        migrations.AddField(
            model_name='project',
            name='techs',
            field=models.CharField(default='HTML', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=django.utils.timezone.get_current_timezone),
        ),
    ]
