# Generated by Django 4.1 on 2022-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainporto', '0002_project_description_project_techs_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='Description'),
        ),
    ]
