# Generated by Django 4.0.5 on 2022-08-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainporto', '0003_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lorem ipsum', max_length=200)),
                ('year', models.CharField(default='2002', max_length=50)),
                ('issuedBy', models.CharField(default='Puspresnas', max_length=300)),
            ],
        ),
    ]
