# Generated by Django 4.0.5 on 2022-08-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainporto', '0004_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='issuedBy',
        ),
        migrations.AddField(
            model_name='achievement',
            name='desc',
            field=models.TextField(default='Puspresnas'),
        ),
    ]
